name = "ScientificNotation"
uuid = "ce6368c0-65d3-4606-b925-7b8211f60f4e"
authors = ["Akio TOMIYA <akio.tomiya@hotmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
